"""
Django settings for the justice_rollon project.

Generated by 'django-admin startproject' using Django 5.2.7.

This file contains all configuration for the Django project, including
installed apps, middleware, database, security settings, and third-party
integrations.

For full documentation:
- Settings overview: https://docs.djangoproject.com/en/5.2/topics/settings/
- Complete settings reference: https://docs.djangoproject.com/en/5.2/ref/settings/
- Deployment checklist: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
"""

from pathlib import Path
import os

# =============================================================================
# PROJECT PATHS
# =============================================================================
# Base directory of the project (two levels up from this file: justice_rollon/settings.py)
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY & ENVIRONMENT SETTINGS
# =============================================================================
# SECURITY WARNING: Keep the secret key secret in production!
# In production, override this with a secure value via environment variable.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-(ga8a8#lk8fk9yfb463mr^-m3p+@31!e-b7vf6l1%nb@fn61%4'
)

# SECURITY WARNING: Do not enable DEBUG in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allowed hosts for the application
# Comma-separated list via environment variable, defaults to local development
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Automatically add Render's external hostname (used in production on Render.com)
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    render_hostname = os.environ['RENDER_EXTERNAL_HOSTNAME']
    if render_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_hostname)


# =============================================================================
# AUTHENTICATION
# =============================================================================
# Use custom User model defined in core app instead of Django's default
AUTH_USER_MODEL = 'core.User'


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',          # Django REST Framework for API endpoints
    'corsheaders',             # Handles Cross-Origin Resource Sharing

    # Local apps
    'core',                    # Main application containing models, views, etc.
]


# =============================================================================
# MIDDLEWARE CONFIGURATION
# =============================================================================
MIDDLEWARE = [
    # CORS must be first to handle preflight requests properly
    'corsheaders.middleware.CorsMiddleware',

    # Core Django middleware
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise for serving static files in production (must be after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =============================================================================
# URL & TEMPLATES CONFIGURATION
# =============================================================================
ROOT_URLCONF = 'justice_rollon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add project-level template directories here if needed
        'APP_DIRS': True,  # Allows templates inside individual apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'justice_rollon.wsgi.application'


# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Suitable for development; switch to PostgreSQL in production
    }
}


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
# Enforces strong passwords for user accounts
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'  # Consider changing to project-relevant timezone in production
USE_I18N = True
USE_TZ = True


# =============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# =============================================================================
# Directory where collectstatic will gather all static files (for production)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL prefix for static files
STATIC_URL = '/static/'  # Use 'static/' in development

# Optional: Additional directories for static files (e.g., node_modules)
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# =============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# =============================================================================
# Uses 64-bit integers for auto-incrementing primary keys (recommended)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# CROSS-ORIGIN RESOURCE SHARING (CORS) SETTINGS
# =============================================================================
# Allow frontend (e.g., WordPress on LocalWP or deployed site) to communicate with Django API
CORS_ALLOW_ALL_ORIGINS = False  # Security: Never allow all origins in production

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:10013",        # LocalWP default port
    "http://localhost:10013",
    "http://justicerollon.local",    # Your LocalWP site domain
    "https://justice-18k5.onrender.com",  # Production frontend URL
]

# Allow CSRF-trusted origins for POST requests from these domains
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:10013",
    "http://localhost:10013",
    "http://justicerollon.local",
    "https://justice-18k5.onrender.com",
]

# Required when sending cookies/auth credentials across origins
CORS_ALLOW_CREDENTIALS = True

# Explicitly allow necessary headers (helps with auth tokens and CSRF)
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-requested-with",
]


# =============================================================================
# FILE STORAGE CONFIGURATION (Django 4.2+ STORAGES setting)
# =============================================================================
# Configures how static and uploaded files are stored
STORAGES = {
    # Static files storage using WhiteNoise with manifest and compression
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    # Default storage for user-uploaded media files (e.g., evidence uploads)
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Optional: Define MEDIA settings if handling user uploads
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')